import os
import json

BOOKS_DIR = "books"
MANIFEST_FILE = "books/manifest.json"

def get_metadata(path):
    """Reads meta.json if it exists, otherwise generates defaults."""
    meta_path = os.path.join(path, "meta.json")
    default_name = os.path.basename(path).replace("_", " ").title()
    
    meta = {
        "title": default_name,
        "author": "Unknown",
        "tags": [],
        "blurb": ""
    }
    
    if os.path.exists(meta_path):
        try:
            with open(meta_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                meta.update(data)
        except Exception as e:
            print(f"Error reading metadata for {path}: {e}")
            
    return meta

def build_tree(current_path):
    """Recursively scans directories to build the manifest tree."""
    name = os.path.basename(current_path)
    
    # Check if this directory is a "Book" (contains index.html generated by our tool)
    # We explicitly check for 'index.html' and 'interactive_book.js' to be sure
    if os.path.exists(os.path.join(current_path, "index.html")) and \
       os.path.exists(os.path.join(current_path, "interactive_book.js")):
        meta = get_metadata(current_path)
        return {
            "type": "book",
            "name": name,
            "path": current_path.replace("\\", "/").replace("books/", ""), # Relative path for URL
            "cover": "cover.jpg" if os.path.exists(os.path.join(current_path, "cover.jpg")) else None,
            "meta": meta
        }

    # Otherwise, treat as a Directory
    children = []
    try:
        # Sort children to keep order consistent
        for entry in sorted(os.listdir(current_path)):
            full_entry_path = os.path.join(current_path, entry)
            if os.path.isdir(full_entry_path) and entry != "contents" and entry != "images": 
                # recursion
                child_node = build_tree(full_entry_path)
                if child_node:
                    children.append(child_node)
    except PermissionError:
        pass

    # If it's a directory but has no relevant children, ignoring might be better, 
    # but for now we return the dir node.
    if current_path == BOOKS_DIR: # Root
        return {
            "type": "dir", 
            "name": "books", 
            "path": "", 
            "children": children
        }
    
    if not children:
        return None 

    return {
        "type": "dir",
        "name": name,
        "path": current_path.replace("\\", "/").replace("books/", ""),
        "cover": None, # Dirs could scan children for a cover, but simplified to None
        "children": children
    }

def generate():
    print("Generating manifest...")
    tree = build_tree(BOOKS_DIR)
    
    with open(MANIFEST_FILE, "w", encoding="utf-8") as f:
        json.dump(tree, f, indent=2)
    print(f"Manifest written to {MANIFEST_FILE}")

if __name__ == "__main__":
    generate()
